version: '3.9'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - ../foodgram_app/postgres_data:/var/lib/postgres/data
    env_file:
      - ./.env

  backend:
    container_name: foodgram-backend
    image: ghoulnec/foodgram-backend:latest
    volumes:
      - ../foodgram_app/static_value:/app/static_backend/
      - ../foodgram_app/media_value:/app/media_backend/
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    container_name: foodgram-frontend
    image: ghoulnec/foodgram-frontend:latest
    volumes:
      - ../foodgram_app/frontend/:/app/result_build/
    depends_on:
      - backend
    env_file:
      - ./.env

  nginx:
    container_name: foodgram-nginx
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../foodgram_app/frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - ../foodgram_app/static_value:/var/www/static_backend/
      - ../foodgram_app/media_value:/var/www/media_backend/
    depends_on:
      - frontend

volumes:
  postgres_data:
  static_value:
  media_value:
